-- Create a database hbtn_0d_usa database and state table with id and name as descriptions
-- id should be unique, autogenerated, not nul and a primary key
-- name should not be nul. If both database and table exist, script should not fail

CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.states (
	id INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
	name VARCHAR(256) NOT NULL

);
